name: Update develop branch with every push to main

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-master-back-to-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Merge main back to develop
      run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff main -m "Auto-merge main back to develop"
          git push
